#!/usr/bin/env python
#
# Copyright 2017 Platform9 Systems Inc. (http://www.platform9.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys

from checks import checks
import client as k8s


def server_version():
    r = k8s.get('version')
    j = r.json()
    return '.'.join([j['major'], j['minor']])


def run_checks(from_ver, to_ver):
    results = []
    for affected_ver, action_required, check in checks:
        if from_ver >= affected_ver or to_ver < affected_ver:
            continue
        ok, msg = check()
        results.append((affected_ver, ok, action_required, msg))
    return results


def report(results):
    by_version = sorted(results, key=lambda res: res[0])
    by_action_required = sorted(by_version, key=lambda res: res[2])
    for affected_ver, ok, action_required, msg in by_action_required:
        if not ok:
            print ok, affected_ver, action_required, msg


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print "Usage: %s VERSION (e.g. 1.6)"
        print "Ensure kubectl proxy is listening on localhost:8001"
        sys.exit(1)
    from_ver = server_version()
    to_ver = sys.argv[1]
    print "checking for pre-upgrade actions advised for upgrade from %s to %s" % (from_ver, to_ver)
    results = run_checks(from_ver, to_ver)
    report(results)
